PUT http://localhost:5000/api/addcards
Content-Type: application/json

{
    "_id": "6484a059700a31b55fa81014",
    "name": "new-deck1",
    "cards": [
        {
            "question": "Dog",
            "answer": "No",
            "tries": [0, 0, 0],
            "lastTry": "2023-06-08T21:15:20-06:00"
        }
    ]
}